using System;
using System.Collections;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;
using System.Data.SqlClient;

namespace Dist_Cloud
{


    public partial class registration : System.Web.UI.Page
    {
        DBConn db = new DBConn(new nodeDB().masterDB);
        keyGen k = new keyGen();

        SendMAIL sm = new SendMAIL();

        dataE ken = new dataE();
        protected void Page_Load(object sender, EventArgs e)
        {
            //Button3.Enabled = false;
            err1.Visible = false;
        }
        protected void Button1_Click(object sender, EventArgs e)
        {
            db.con.Open();

            db.con.Close();

        }
        protected void Button3_Click(object sender, EventArgs e)
        {
            try
            {
                int id;
                db.con.Open();
                id = db.getCurrentID("regTABLE");
                db.InsertData("INSERT INTO regTABLE VALUES('" + id + "','" + fname.Text + "','" + mName.Text + "','" + lName.Text + "','" + gender.Text + "','" + dob.Text + "','" + addr1.Text + "','" + addr2.Text + "','" + email.Text + "','" + (cntcode.Text + mob.Text) + "','" + pass.Text + "')");
                db.con.Close();

                string key;
                key = k.createKey(fname.Text, lName.Text);
                string fskey = ken.Encrypt(key, true, email.Text);

                Session["FNAME"] = fname.Text;
                Session["MNAME"] = mName.Text;
                Session["LNAME"] = lName.Text;
                Session["UID"] = email.Text;





                db.con.Open();
                id = db.getCurrentID("skeyTABLE");
                db.InsertData("INSERT INTO skeyTABLE VALUES('" + id + "','" + email.Text + "','" + fskey + "')");
                db.con.Close();

                err0.Text = "Your Autogenerated Key:" + key;
                err1.Text = sm.SendEmail(email.Text, "DROPS' Registration ", "Welcome " + (fname.Text + " " + lName.Text) + " \nYour autogenerated shared key:" + fskey);

                err.Text = "You Registered Successfully..";

            }
            catch (Exception ex)
            {
                err.Text = ex.Message.ToString();
            }

        }
        protected void Button2_Click(object sender, EventArgs e)
        {

        }
    }
}